name: Build and Push Images

on:
  workflow_call:
  workflow_dispatch:

jobs:
  impromat-app:
    uses: ./.github/workflows/shared-build-and-push-image-job.yml
    with:
      packageName: impromat
      dockerfilePath: packages/infrastructure/Dockerfile-impromat-app

  impromat-api:
    uses: ./.github/workflows/shared-build-and-push-image-job.yml
    with:
      packageName: impromat-api
      dockerfilePath: packages/infrastructure/Dockerfile-impromat-api
