name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: git fetch
      - run: git checkout $BRANCH_NAME
      - run: ls -la
      - run: git --version
      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.DOKKU_PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.IMPROMAT_SERVER_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Print Branch Name
        run: echo "$BRANCH_NAME"
      - run: git status
      - run: git remote add impromat-app-production dokku@impromat.app:impromat-app-production
      - run: git push impromat-app-production $BRANCH_NAME:master
      # - name: Add remotes
      #   run: |
      #     git remote add impromat-app-production dokku@impromat.app:impromat-app-production
      #     git remote add impromat-api-production dokku@impromat.app:impromat-api-production
      #     git push impromat-app-production $BRANCH_MASTER:master
