name: Development Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency: development-environment

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  test:
    uses: ./.github/workflows/shared-test-job.yml

  deploy-development:
    needs:
      - test
    uses: ./.github/workflows/shared-deploy-job.yml
    secrets: inherit
    with:
      environment: development

  e2e-test:
    needs:
      - deploy-development
    uses: ./.github/workflows/shared-e2e-test-job.yml
    secrets: inherit
