name: Development Improbib Import

on:
  workflow_dispatch:
    inputs:
      useCommitOfAction:
        type: boolean
        default: false
      useCache:
        type: boolean
        default: true

jobs:
  improbib-import:
    uses: ./.github/workflows/shared-improbib-import.yml
    secrets:
      improbibUserAccessToken: ${{ secrets.DEV_IMPROBIB_ACCESS_TOKEN }}
    with:
      environment: development
      checkoutEnvironment: ${{ inputs.useCommitOfAction }}
      useCache: ${{ inputs.useCache }}
      apiEndpoint: https://api.dev.impromat.app
