name: Development Deployment

on:
  workflow_dispatch:
  push: # TODO remove after testing

concurrency: development-environment

jobs:
  deploy-development:
    uses: ./.github/workflows/shared-deploy-job.yml
    secrets: inherit
    with:
      environment: development

  e2e-test:
    needs:
      - deploy-development
    uses: ./.github/workflows/shared-e2e-test-job.yml
    secrets: inherit
