name: Development Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

concurrency: development-environment

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  test:
    uses: ./.github/workflows/test-job.yml

  deploy:
    needs:
      - test
    uses: ./.github/workflows/deploy-job.yml
    secrets: inherit
    with:
      environment: development

  e2e-test:
    needs:
      - deploy
    uses: ./.github/workflows/e2e-test-job.yml
    secrets: inherit
