name: Shared E2E Test Job

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - name: Run End-to-End Tests
        run: yarn impromat test:e2e
        env:
          BASE_URL: https://dev.impromat.app/
          COOKIE_DOMAIN: api.dev.impromat.app
          COOKIE_SECRET: ${{ secrets.DEV_E2E_COOKIE_SECRET }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: "**/junit-results.xml"
