name: Production Deployment

on:
  push:
    branches:
      - main

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  test:
    uses: ./.github/workflows/test-job.yml
    with:
      commitSha: ${{ needs.increase-build-version.outputs.commitSha }}

  deploy:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Print last commit message
        run: |
          lastCommitMessage=$(git log -1 --oneline)
          echo "lastCommitMessage=$lastCommitMessage"
      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.DOKKU_PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.IMPROMAT_SERVER_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Print Branch Name
        run: echo "$BRANCH_NAME"
      - run: git remote add impromat-app-production dokku@impromat.app:impromat-app-production
      - run: git remote add impromat-api-production dokku@impromat.app:impromat-api-production
      - run: git push impromat-app-production $BRANCH_NAME:master --force
      - run: git push impromat-api-production $BRANCH_NAME:master --force
