name: Changeset Release

on:
  push:
    branches:
      - changeset-release/main

jobs:
  statusCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Add status check
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              context: 'test-report',
              description: 'Generated status check for release pipeline'
            })

