name: Release

on:
  push:
    branches:
      - dev

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Restore .yarn release cache
        uses: actions/cache/restore@v3
        with:
          path: ./.yarn/cache
          key: yarn-release-cache

      - name: Install Dependencies
        run: yarn install

      - name: Save .yarn release cache
        uses: actions/cache/save@v3
        with:
          path: ./.yarn/cache
          key: yarn-release-cache

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn ci:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: echo "Publish"
