name: Changeset Release

on:
  workflow_run:
    workflows: [Release]
    # branches: [main]
    types:
      - completed

jobs:
  statusCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: refs/heads/changeset-release/main
      - name: Get SHA of branch
        id: get_sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"
      - name: Add status check
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ steps.get_sha.outputs.sha }}',
              state: 'success',
              context: 'test-report',
              description: 'Generating status check for release pipeline'
            })
