name: Shared Deployment Job

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  configure-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.DOKKU_PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.IMPROMAT_SERVER_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Configure Enviroment
        run: bash -e ./packages/infrastructure/configure-${{ inputs.environment }}.sh
        env:
          DEBUG: 1

  build-impromat-app:
    needs: configure-environment
    uses: ./.github/workflows/shared-build-and-push-image-job.yml
    with:
      packageName: impromat
      dockerfilePath: packages/infrastructure/Dockerfile-impromat-app

  build-impromat-api:
    needs: configure-environment
    uses: ./.github/workflows/shared-build-and-push-image-job.yml
    with:
      packageName: impromat-api
      dockerfilePath: packages/infrastructure/Dockerfile-impromat-api
  
  deploy-impromat-app:
    runs-on: ubuntu-latest
    needs:
      - build-impromat-app
    steps:
      - name: Setup Dokku SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.DOKKU_PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.IMPROMAT_SERVER_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - run: ssh dokku@impromat.app git:from-image impromat-app-${{inputs.environment}} ${{ needs.build-impromat-app.outputs.image }}

  deploy-impromat-api:
    runs-on: ubuntu-latest
    needs:
      - build-impromat-api
    steps:
      - name: Setup Dokku SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.DOKKU_PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.IMPROMAT_SERVER_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - run: ssh dokku@impromat.app git:from-image impromat-api-${{inputs.environment}} ${{ needs.build-impromat-api.outputs.image }}
