name: Shared Test Job

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - run: yarn install
      - run: yarn codegen
      - run: |
          if git diff-index --quiet HEAD --; then
              echo "Codegen produced changes. Please run 'yarn codegen' and commit changes."
              exit 1
          fi
        name: Test if codegen has been run

      - run: yarn workspace:lint
      - run: yarn workspace:build
      - name: Run tests for all packages
        run: yarn workspace:test
        env:
          DEBUG: pw:webserver
      - name: Print backend infrastructure logs if tests failed
        if: failure()
        run: yarn docker-compose:logs
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: "**/*unit-results.xml"
      - uses: actions/upload-artifact@v3
        name: Publish Impromat Unit Test Report
        if: always()
        with:
          name: playwright-impromat-screenshots
          path: packages/impromat/playwright-report
          retention-days: 30
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          sha: ${{ github.sha }}
          context: test-report
