name: Build and Push Images

on:
  workflow_call:
    inputs:
      packageName:
        required: true
        type: string
      dockerfilePath:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 20
    outputs:
      image: ${{ steps.image_output.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read version from package.json
        id: version
        run: echo "version=$(node -p 'require("./packages/${{ inputs.packageName }}/package.json").version')" >> $GITHUB_ENV

      - id: image_prefix
        run: echo "image_prefix=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ inputs.packageName }}" >> $GITHUB_ENV

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: $image_prefix
          tags: |
            type=ref,event=branch,prefix=$version-,suffix=-${{github.run_number}}
            type=ref,event=pr,prefix=$version-pr-,suffix=-${{github.run_number}}
            type=semver,pattern={{version}},value=$version,enable={{is_default_branch}}
            # set latest tag for main
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            ${{ github.ref != 'refs/heads/main' && 'development=1' }}

      - name: Construct app version
        id: app-version
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "APP_VERSION=$version-$RANDOM" >> $GITHUB_ENV
          else
            echo "APP_VERSION=$version" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ inputs.dockerfilePath }}
          build-args: |
            VITE_VERSION=$APP_VERSION
            VERSION=$APP_VERSION

      - name: Set image output
        id: image_output
        run: echo "image=$image_prefix:$DOCKER_METADATA_OUTPUT_VERSION" >> $GITHUB_OUTPUT
