name: Shared Test Job

on:
  workflow_call:
    inputs:
      commitSha:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print commit SHA
        run: "echo ${{ inputs.commitSha }}"
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitSha }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - name: Publish test report from impromat app
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: packages/impromat/playwright-report
          path: packages/impromat/playwright-report/
          retention-days: 30
