name: Test Pull Request

on:
  pull_request:
    branches:
      []
      # - dev

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  test:
    uses: ./.github/workflows/test-job.yml
    with:
      commitSha: ${{ github.sha }}
