name: Shared Test Job

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      # TODO compare cache runtimes with cache:yarn feature from setup-node
      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      # - uses: actions/cache@v3
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      - run: yarn install --immutable

      - run: yarn workspace:lint
      - run: yarn workspace:build
      # FIXME e2e infrastructure is not started with the yarn workspace:test
      # command because the alias is not working
      # only start if required by impromat-api or impromat
      - name: Start infrastructure for e2e tests
        run: docker compose --profile backend up --wait
        working-directory: ./packages/infrastructure/
      - name: Run tests for all packages
        run: |
          shopt -s expand_aliases
          alias docker-compose="docker compose"
          docker-compose version
          yarn docker-compose version
          yarn workspace:test
        env:
          DEBUG: pw:webserver
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: "**/junit-results.xml"
